### PR TITLE
feat(moderation): Rules

### PR DESCRIPTION
**Pull request by Uncommon-34**
Rules is a system where if a user sends a message with out member role the message is deleted and there prompted via dm to accept the rules. a message in the rules channel with I accept button

### CODE REVIEW

**Comment by Pkmmte** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/Wave-Play/robo.js/blob/main/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by Uncommon-34** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Uncommon-34** [comment]
recheck

**Review by Pkmmte — APPROVED** [review]
Looks and works overall really well! I did have to change a few things and bring the code style up to our monorepo guidelines, however. Also made a few copy changes.

**Pull request merged**
