### PR TITLE
Added primitive support for user installs

### PR DESCRIPTION
**Pull request by bloomsirenix**
I did not test it yet inside of robo.js but it worked outside using my own code pkmmte agreed on me trying to contribute it into this amazing framework!

### CODE REVIEW

**Comment by Pkmmte** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/Wave-Play/robo.js/blob/main/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by bloomsirenix** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by bloomsirenix** [comment]
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/Wave-Play/robo.js/blob/main/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> I have read the CLA Document and I hereby sign the CLA
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request


I have read the CLA Document and I hereby sign the CLA

**Comment by Pkmmte** [comment]
Thank you for this, it works great!

**Pull request merged**
