### PR TITLE
(added to Docs) windows Execution Policies

### PR DESCRIPTION
**Pull request by Uncommon-34**
added a description and how to fix the issues with windows and there Execution Policies. this is mainly for newbies like myself

### CODE REVIEW

**Review by Pkmmte — CHANGES_REQUESTED** [review]
Would you mind removing the changeset from this PR? Don't wanna accidentally trigger a new release for the moderation plugin again.

**Comment by Uncommon-34** [comment]
how do i do this i didn't notice these changes where still attached?

**Comment by Uncommon-34** [comment]
I believe I changed it I don't even know what that was sorry

**Comment by Nazeofel** [comment]
Hey, just for informations changeset are basically the versioning system ^^, it would trigger a release if it includes one

**Review by Pkmmte — APPROVED** [review]

**Pull request merged**
