### PR TITLE
📖 Documentation: Tweaks

### PR DESCRIPTION
**Pull request by ArnavK-09**
# Some Tweaks In Documentation

- [x] Add GH Button
- [x] Prettier Whole Docs Base
- [x] Add Admonitions
- [x] Add File Names
- [x] Add Line Numbers for demo files
- [x] Highlight Important Things
- [x] Fix Old Dir `.config/robo.mjs` -> `config/robo.mjs`
- [x] Add Footer Text
- [x] Changed package.json name
- [x] Add Production Site URL In Config
- [x] Add Tabs for TS/JS Examples

### CODE REVIEW

**Comment by ArnavK-09** [comment]
### @Pkmmte can you review it?

> ## Can you tell me which code example should I add for Tabs `JavaScript | Typescript` to compare??

image

**Comment by Pkmmte** [comment]
@ArnavK-09 Thank you for this! It'll take me a bit to review it all, but it's looking good so far!

As for the language tabs: all existing examples are in JavaScript. Anything that's not Robo config related (.mjs) should ideally include a typescript variant with the types to use. 

We can start with just adding types to the `export const config` objects so they're more like: `export const config: CommandConfig` (for command file examples). The only other types that come to mind right now are command/event function parameters such as the interaction object (ChatInputCommandInteraction) and whatever other events may be described. (e.g. messageCreate's "message" parameter is type "Message")

**Comment by ArnavK-09** [comment]
> @ArnavK-09 Thank you for this! It'll take me a bit to review it all, but it's looking good so far!
> 
> As for the language tabs: all existing examples are in JavaScript. Anything that's not Robo config related (.mjs) should ideally include a typescript variant with the types to use.
> 
> We can start with just adding types to the `export const config` objects so they're more like: `export const config: CommandConfig` (for command file examples). The only other types that come to mind right now are command/event function parameters such as the interaction object (ChatInputCommandInteraction) and whatever other events may be described. (e.g. messageCreate's "message" parameter is type "Message")
@Pkmmte 

Thanks for helping me out :tada:

#### Can you review it and merge???

**Comment by Pkmmte** [comment]
Merged!

@all-contributors add @ArnavK-09 for documentation

**Pull request merged**
