### PR TITLE
Fix (templates/economy-bot): Bug causing user unable to choose dice number!

### LINKED ISSUE #73: Bot is choosing dice number by own
Templates/economy-bot

### PR DESCRIPTION
**Pull request by ArnavK-09**
### Fixes #73

> - [x] Fixed Economy Bot Template, Unable to Choose number bug!
> - [x] Added **0.5x** multiplier
> - [x] Fix Error thrown on ` /balance ` command if user not registered!

### CODE REVIEW

**Comment by ArnavK-09** [comment]
#SquashIt

**Comment by Nazeofel** [comment]
Hey ! thank you again for contributing !, your PR is almost ready to be merged, one little thing, to asssure quality code we do not accept the use of "any", please change them to the right type.

Remember that you can also aways use the ESLint command to verify those things !.

**Comment by ArnavK-09** [comment]
> Hey ! thank you again for contributing !, your PR is almost ready to be merged, one little thing, to asssure quality code we do not accept the use of "any", please change them to the right type.
> 
> Remember that you can also aways use the ESLint command to verify those things !.

[x] Lint Done
[x] Works on my machine!

**Comment by ArnavK-09** [comment]
> Hey ! thank you again for contributing !, your PR is almost ready to be merged, one little thing, to asssure quality code we do not accept the use of "any", please change them to the right type.
> 
> Remember that you can also aways use the ESLint command to verify those things !.
@Nazeofel 
- [x] Lint Done
- [x] Works on my machine!

**Comment by Nazeofel** [comment]
LGTM ! thank you

**Pull request merged**
