### PR TITLE
💵 New Template: Starter Economy Bot Using Flashcore!

### PR DESCRIPTION
**Pull request by ArnavK-09**
---
I've created a new template named "economy-bot" with **robo.js**, designed to be a simple yet effective starting point for users. This template has been added to the templates folder within your repository.

```js
This contribution aligns with the spirit of #Hacktoberfest. Please #Squash it to `main` branch. Thanks 😊
```

---
> Please review and merge this pull request to make it available to the community. Thank you!

### CODE REVIEW

**Comment by ArnavK-09** [comment]
### Good #69!
> Only /daily & game command left!

**Comment by Pkmmte** [comment]
This is looking pretty cool so far! ÒwÓ

**Comment by ArnavK-09** [comment]
image

**Comment by Pkmmte** [comment]
Oops, forgot to "squash" instead of merging normally. ;-; 

Thanks for the template contribution. I appreciate your use of the Flashcore APIs for this!

**Pull request merged**
