### PR TITLE
Refactor WebSocket Server to Enhance Connection Handling and State Management

### PR DESCRIPTION
**Pull request by yuvraj1107thapa**
### Summary
Refactored the WebSocket server to improve modularity and connection handling.

### Changes Made
- Refactored **3** connection management modules.
- Enhanced liveness checks for **2** connection types.
- Optimized **4** state update mechanisms.
- Added error handling for incoming messages.

### Impact
Improves performance, stability, and maintainability.

### CODE REVIEW

**Comment by Pkmmte** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/Wave-Play/robo.js/blob/main/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by yuvraj1107thapa** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by yuvraj1107thapa** [comment]
recheck

**Comment by Pkmmte** [comment]
Thanks for this PR! I love new the clean look. ✨

Just made two small adjustments. The `key` param in `broadcastUpdate` should be an optional `string[]` rather than `string`. The `cleanKey` is already the pure string version and `key` is meant to be an array for a useEffect-like dependencies array syntax.

Other than that, I also made two other minor adjustments for our syntax preference. (heartbleed ptsd & optional chaining)

**Review by Pkmmte — APPROVED** [review]

**Pull request merged**
