### PR TITLE
🤫 Inclusion of Confessions Plugin & Confessions Bot Template!

### PR DESCRIPTION
**Pull request by ArnavK-09**
---

## Overview

> This PR adds a new Confessions plugin and bot template to Robo.js. 

- **The Confessions plugin allows admins to enable anonymous confessions in their guild. Users can submit confessions via a command, and confessions are filtered to be SFW before posting to a confessions channel.**
- **The confessions-bot template provides a basic bot with the Confessions plugin enabled to demonstrate usage and allow users to easily create a confessions bot.**

## Roadmap

- [x] Implement Confessions plugin
  - [x] `/confess` command to submit confessions
  - [x] SFW filter using regex and word blacklist
  - [x] `/confess-channel` command to set confessions channel
  - [x] Admin commands to enable/manage confessions 
- [x] ~~Create confessions-bot template~~
  - [x] ~~Enable Confessions plugin~~
- [x] Checks 
- [x] Wrap-up
  - [x] Fix Flashcore Error
  - [x] Lint Code
  - [x] Format Code
- [x] Proper README.md
- [x] Publish Package To NPM (automated)

## Usage

The Confessions plugin can be enabled like any other Robo.js plugin. Usage is documented in the README.md.
The confessions-bot template can be used to quickly bootstrap a confessions bot.

---
#### _Contributing To #HacktoberFest_ | #SquashIt | #SwagPlease

### CODE REVIEW

**Comment by Pkmmte** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/Wave-Play/robo.js/blob/main/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by ArnavK-09** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ArnavK-09** [comment]
## Hey Robojs Team,

**I hope you're all having a great Hacktoberfest! I've submitted a pull request for this project that I believe aligns with our goals and standards. It would be fantastic if one of the reviewers could take a look and, if everything checks out, consider merging it into the main branch.**

# #59 

> Your feedback and support are much appreciated. Let's make this Hacktoberfest a success together!

🤫 **Thank you!**

**Comment by ArnavK-09** [comment]
<details>
<summary> #Hacktoberfest </summary>

</details>

**Pull request merged**
